services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: ./requirements/mariadb
    volumes:
      - '/home/ybourais/data/db:/var/www/db'
    networks:
      - network
    restart: on-failure
    env_file:
      - /home/ybourais/inception/srcs/.env
  php-fpm:
    container_name: php-fpm
    image: php-fpm:42
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - '/home/ybourais/data/wp:/var/www/html'
    networks:
      - network
    restart: on-failure
    env_file:
      - /home/ybourais/inception/srcs/.env
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on: 
      - php-fpm
    image: nginx:42
    volumes:
      - '/home/ybourais/data/wp:/var/www/html'
    ports:
      - '443:443'
    networks:
      - network
    restart: on-failure
networks:
    network:
      name: network
      external: true
