services:
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - /home/ybourais/inception/srcs/.env
  php-fpm:
    container_name: php-fpm
    image: php-fpm:42
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always
    env_file:
      - /home/ybourais/inception/srcs/.env
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on: 
      - php-fpm
    image: nginx:42
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - '443:443'
    networks:
      - network
    restart: always
networks:
    network:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ybourais/data/db
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ybourais/data/wp
      o: bind
